export const globalStyles = {
	webkit_scrollbar: {
		width: "5px",
	},
	webkit_scrollbar_track: {
		background: "#ffffff3b",
	},
	webkit_scrollbar_thumb: {
		backgroundColor: "#8f54a0",
	},
	body: {
		fontFamily: "system-ui",
	},
	ul: {
		padding: "0px",
		listStyleType: "none",
		lineHeight: "250%",
	},
	li: {
		padding: "0px",
		listStyleType: "none",
		lineHeight: "250%",
	},
	btn: {
		background: "none",
		border: "none",
		fontSize: "13px",
		height: "26px",
		textDecoration: "none",
	},
	btn_hover: {
		borderBottom: "solid 3px #f5d0ff",
	},
	button_active: {
		height: "100%",
		outline: "none",
		borderTop: "none",
		borderLeft: "none",
		borderRight: "none",
		borderBottom: "solid #e2e600",
		background: "#ff4de160",
		color: "#f5d0ff",
	},
	icon_btn: {
		backgroundColor: "transparent",
	},
	icon__btn_hover: {
		backgroundColor: "rgba(90, 8, 72, 0.52)",
	},
	h1: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	h2: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	h3: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	h4: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	h5: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	h6: {
		margin: "auto",
		padding: "auto",
		fontStyle: "italic",
	},
	"": {
		boxSizing: "border-box",
	},
	window_container: {
		zIndex: "9999",
		position: "fixed",
		width: "50vw",
		height: "50vh",
		minWidth: "324px",
		minHeight: "400px",
		maxHeight: "95vh",
		maxWidth: "95vw",
		resize: "both",
		overflow: "hidden",
		border: "1px solid #000000",
		borderTopLeftRadius: "4px",
		borderTopRightRadius: "4px",
	},
	window_icon: {
		alignSelf: "center",
		objectFit: "contain",
	},
	window_icon_group: {
		alignItems: "center",
		display: "flex",
		flex: "0 1 100%",
		justifyContent: "flex-end",
	},
	window_title_group: {
		justifyContent: "flex-start",
	},
	window_title_text: {
		color: "rgb(255, 255, 255)",
		alignSelf: "center",
		flex: "0 1 100%",
		fontSize: "16px",
		fontWeight: "lighter",
		fontStyle: "oblique",
		marginBottom: "5px",
		marginLeft: "10px",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	window_top: {
		background: "rgb(189, 63, 162)",
		display: "flex",
		padding: "1px 3px",
		width: "100%",
	},
	window_content: {
		display: "flex",
		flexFlow: "column",
		fontSize: "14px",
		color: "rgb(207, 207, 207)",
		height: "100%",
	},
	window_content__main_cont: {
		flex: "1 1 auto",
		padding: "10px",
		overflowX: "auto",
		width: "100%",
	},
	main_cont: {
		backgroundColor: "rgba(0, 0, 0, 0.767)",
	},
	window_content__window_menu: {
		flex: "0 1 40px",
		backgroundColor: "rgb(112, 42, 97)",
		position: "sticky",
		width: "100%",
		bottom: "0",
	},
	window_menu__btn: {
		height: "100%",
		padding: "5px",
		color: "#f5d0ff",
		textAlign: "center",
		textDecoration: "none",
	},
	trigger: {
		zIndex: "1500",
		position: "fixed",
		bottom: "0.5em",
		margin: "10px",
		color: "white",
		width: "10%",
		height: "auto",
		background: "none",
		border: "none",
	} as React.CSSProperties,
}
